import "dotenv/config";
import { neon } from "@neondatabase/serverless";

const databaseUrl = process.env.DATABASE_URL || process.env.NETLIFY_DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL or NETLIFY_DATABASE_URL environment variable is required");
}
const sql = neon(databaseUrl);

const vehicleData: Record<string, { manufacturer: string; realModel: string }> = {
  "Asbo": { manufacturer: "Maxwell", realModel: "Vauxhall Corsa" },
  "Blista": { manufacturer: "Dinka", realModel: "Honda Civic" },
  "Blista Kanjo": { manufacturer: "Dinka", realModel: "Honda Civic EK9 Type R" },
  "Brioso R/A": { manufacturer: "Grotti", realModel: "Fiat 500 Abarth" },
  "Brioso 300": { manufacturer: "Grotti", realModel: "Fiat 500 Abarth" },
  "Brioso 300 Large": { manufacturer: "Grotti", realModel: "Fiat 500 Widebody" },
  "Club": { manufacturer: "BF", realModel: "Volkswagen Golf GTI Mk2" },
  "Dilettante": { manufacturer: "Karin", realModel: "Toyota Prius" },
  "Issi": { manufacturer: "Weeny", realModel: "Mini Cooper / Smart ForTwo" },
  "Issi Classique": { manufacturer: "Weeny", realModel: "Austin Mini" },
  "Panto": { manufacturer: "Benefactor", realModel: "Smart ForTwo" },
  "Prairie": { manufacturer: "Bollokan", realModel: "Hyundai Veloster" },
  "Rhapsody": { manufacturer: "Declasse", realModel: "AMC Pacer" },
  "Weevil": { manufacturer: "BF", realModel: "Volkswagen Beetle" },
  "Oracle XS": { manufacturer: "Ubermacht", realModel: "BMW 7 Series E38" },
  "Fathom FR36": { manufacturer: "Fathom", realModel: "Infiniti Q50" },
  "Zion Cabrio": { manufacturer: "Ubermacht", realModel: "BMW 6 Series Convertible" },
  "Zion": { manufacturer: "Ubermacht", realModel: "BMW 6 Series E63" },
  "Windsor Drop": { manufacturer: "Enus", realModel: "Rolls-Royce Dawn" },
  "Windsor": { manufacturer: "Enus", realModel: "Rolls-Royce Wraith" },
  "Sentinel": { manufacturer: "Ubermacht", realModel: "BMW M3 E92" },
  "Sentinel XS": { manufacturer: "Ubermacht", realModel: "BMW M3 E46" },
  "Previon": { manufacturer: "Karin", realModel: "Honda Prelude" },
  "Oracle": { manufacturer: "Ubermacht", realModel: "BMW 7 Series E65" },
  "Jackal": { manufacturer: "Ocelot", realModel: "Jaguar XK" },
  "Felon GT": { manufacturer: "Lampadati", realModel: "Maserati GranTurismo Cabrio" },
  "Felon": { manufacturer: "Lampadati", realModel: "Maserati Quattroporte" },
  "F620": { manufacturer: "Benefactor", realModel: "Mercedes-Benz SL65 AMG" },
  "Exemplar": { manufacturer: "Dewbauchee", realModel: "Aston Martin Rapide" },
  "Cognoscenti Cabrio": { manufacturer: "Enus", realModel: "Bentley Continental GTC" },
  "Asea": { manufacturer: "Declasse", realModel: "Chevrolet Aveo" },
  "Asterope": { manufacturer: "Karin", realModel: "Toyota Camry" },
  "Cognoscenti": { manufacturer: "Enus", realModel: "Bentley Flying Spur" },
  "Cognoscenti 55": { manufacturer: "Enus", realModel: "Bentley Mulsanne" },
  "Emperor": { manufacturer: "Albany", realModel: "Cadillac DeVille" },
  "Emperor (Rouillée)": { manufacturer: "Albany", realModel: "Cadillac DeVille (Rusty)" },
  "Emperor (Enneigée)": { manufacturer: "Albany", realModel: "Cadillac DeVille (Snow)" },
  "Fugitive": { manufacturer: "Cheval", realModel: "Chevrolet Impala" },
  "Glendale": { manufacturer: "Benefactor", realModel: "Mercedes-Benz W114" },
  "Glendale Custom": { manufacturer: "Benefactor", realModel: "Mercedes-Benz W114 Custom" },
  "Ingot": { manufacturer: "Vulcar", realModel: "Volvo V70" },
  "Intruder": { manufacturer: "Karin", realModel: "Lexus GS300" },
  "Premier": { manufacturer: "Declasse", realModel: "Chevrolet Cobalt" },
  "Primo": { manufacturer: "Albany", realModel: "Cadillac Cimarron" },
  "Primo Custom": { manufacturer: "Albany", realModel: "Cadillac Cimarron Custom" },
  "Regina": { manufacturer: "Dundreary", realModel: "Mercury Grand Marquis Wagon" },
  "Corbillard Romero": { manufacturer: "Albany", realModel: "Cadillac Hearse" },
  "Schafter": { manufacturer: "Benefactor", realModel: "Mercedes-Benz E-Class W212" },
  "Stafford": { manufacturer: "Enus", realModel: "Rolls-Royce Phantom" },
  "Stanier": { manufacturer: "Vapid", realModel: "Ford Crown Victoria" },
  "Stratum": { manufacturer: "Zirconium", realModel: "Honda Accord Wagon" },
  "Stretch": { manufacturer: "Dundreary", realModel: "Lincoln Town Car Limo" },
  "Super Diamond": { manufacturer: "Enus", realModel: "Rolls-Royce Phantom" },
  "Surge": { manufacturer: "Cheval", realModel: "Chevrolet Volt" },
  "Tailgater": { manufacturer: "Obey", realModel: "Audi A4" },
  "Tailgater S": { manufacturer: "Obey", realModel: "Audi RS4" },
  "Warrener": { manufacturer: "Vulcar", realModel: "Nissan Skyline C10" },
  "Warrener HKR": { manufacturer: "Vulcar", realModel: "Nissan Skyline C10 Race" },
  "Washington": { manufacturer: "Albany", realModel: "Cadillac DeVille" },
  "Rhinehart": { manufacturer: "Benefactor", realModel: "Mercedes-Benz S-Class" },
  "Scharmann": { manufacturer: "Benefactor", realModel: "Mercedes-Maybach S-Class" },
  "Asterope GZ": { manufacturer: "Karin", realModel: "Toyota Camry TRD" },
  "Deity": { manufacturer: "Enus", realModel: "Cadillac CT5-V Blackwing" },
  "Baller": { manufacturer: "Gallivanter", realModel: "Range Rover Sport" },
  "Baller II": { manufacturer: "Gallivanter", realModel: "Range Rover Sport" },
  "Baller LE": { manufacturer: "Gallivanter", realModel: "Range Rover" },
  "Baller LE LWB": { manufacturer: "Gallivanter", realModel: "Range Rover LWB" },
  "BeeJay XL": { manufacturer: "Karin", realModel: "Toyota FJ Cruiser" },
  "Cavalcade": { manufacturer: "Albany", realModel: "Cadillac Escalade" },
  "Cavalcade II": { manufacturer: "Albany", realModel: "Cadillac Escalade ESV" },
  "Contender": { manufacturer: "Vapid", realModel: "Ford F-150" },
  "Dubsta": { manufacturer: "Benefactor", realModel: "Mercedes-Benz G-Class" },
  "Dubsta II": { manufacturer: "Benefactor", realModel: "Mercedes-Benz G63 AMG" },
  "Fathom FQ 2": { manufacturer: "Fathom", realModel: "Infiniti FX35" },
  "Granger": { manufacturer: "Declasse", realModel: "Chevrolet Suburban" },
  "Gresley": { manufacturer: "Bravado", realModel: "Jeep Grand Cherokee" },
  "Habanero": { manufacturer: "Emperor", realModel: "Lexus RX350" },
  "Huntley S": { manufacturer: "Enus", realModel: "Bentley Bentayga" },
  "Landstalker": { manufacturer: "Dundreary", realModel: "Ford Explorer" },
  "Landstalker XL": { manufacturer: "Dundreary", realModel: "Ford Expedition" },
  "Mesa": { manufacturer: "Canis", realModel: "Jeep Wrangler" },
  "Novak": { manufacturer: "Lampadati", realModel: "Maserati Levante" },
  "Patriot": { manufacturer: "Mammoth", realModel: "Hummer H2" },
  "Patriot Stretch": { manufacturer: "Mammoth", realModel: "Hummer H2 Limo" },
  "Radius": { manufacturer: "Vapid", realModel: "Ford Edge" },
  "Rebla GTS": { manufacturer: "Ubermacht", realModel: "BMW X6 M" },
  "Rocoto": { manufacturer: "Obey", realModel: "Audi Q7" },
  "Seminole": { manufacturer: "Canis", realModel: "Jeep Cherokee XJ" },
  "Seminole Frontier": { manufacturer: "Canis", realModel: "Jeep Cherokee XJ" },
  "Serrano": { manufacturer: "Benefactor", realModel: "Mercedes-Benz ML350" },
  "Toros": { manufacturer: "Pegassi", realModel: "Lamborghini Urus" },
  "Astron": { manufacturer: "Pfister", realModel: "Porsche Cayenne" },
  "XLS": { manufacturer: "Benefactor", realModel: "Mercedes-Benz GLE" },
  "I-Wagen": { manufacturer: "Obey", realModel: "Audi e-tron" },
  "Baller ST": { manufacturer: "Gallivanter", realModel: "Range Rover Sport" },
  "Granger 3600LX": { manufacturer: "Declasse", realModel: "Chevrolet Tahoe" },
  "Issi Rallye": { manufacturer: "Weeny", realModel: "Mini Cooper Rally" },
  "Jubilee": { manufacturer: "Enus", realModel: "Rolls-Royce Cullinan" },
  "Aleutian": { manufacturer: "Bravado", realModel: "Dodge Durango" },
  "Cavalcade XL": { manufacturer: "Albany", realModel: "Cadillac Escalade ESV" },
  "Dorado": { manufacturer: "Albany", realModel: "Cadillac Lyriq" },
  "Vivanite": { manufacturer: "Declasse", realModel: "Chevrolet Blazer EV" },
  "Baller ST-D": { manufacturer: "Gallivanter", realModel: "Range Rover Sport Defender" },
  "Alpha": { manufacturer: "Albany", realModel: "Buick Avista Concept" },
  "Banshee": { manufacturer: "Bravado", realModel: "Dodge Viper" },
  "Bestia GTS": { manufacturer: "Grotti", realModel: "Ferrari FF" },
  "Blista Compact": { manufacturer: "Dinka", realModel: "Honda CR-X" },
  "Buffalo": { manufacturer: "Bravado", realModel: "Dodge Charger" },
  "Buffalo S": { manufacturer: "Bravado", realModel: "Dodge Charger SRT" },
  "Calico GTF": { manufacturer: "Karin", realModel: "Toyota Celica GT-Four" },
  "Carbonizzare": { manufacturer: "Grotti", realModel: "Ferrari California" },
  "Comet": { manufacturer: "Pfister", realModel: "Porsche 911 (996)" },
  "Comet Rétro Custom": { manufacturer: "Pfister", realModel: "Porsche 911 (930) RWB" },
  "Comet Safari": { manufacturer: "Pfister", realModel: "Porsche 911 Safari" },
  "Comet S2": { manufacturer: "Pfister", realModel: "Porsche 911 (992)" },
  "Comet SR": { manufacturer: "Pfister", realModel: "Porsche 911 GT3 RS" },
  "Coquette": { manufacturer: "Invetero", realModel: "Chevrolet Corvette C7" },
  "Coquette D10": { manufacturer: "Invetero", realModel: "Chevrolet Corvette C8" },
  "Cypher": { manufacturer: "Ubermacht", realModel: "BMW M4 F82" },
  "Tampa Drift": { manufacturer: "Declasse", realModel: "Ford Maverick Drift" },
  "Elegy RH8": { manufacturer: "Annis", realModel: "Nissan GT-R R35" },
  "Elegy Rétro Custom": { manufacturer: "Annis", realModel: "Nissan Skyline GT-R R32" },
  "Euros": { manufacturer: "Annis", realModel: "Nissan Silvia S15" },
  "Feltzer": { manufacturer: "Benefactor", realModel: "Mercedes-Benz SL55 AMG" },
  "Flash GT": { manufacturer: "Vapid", realModel: "Ford Focus RS" },
  "Furore GT": { manufacturer: "Lampadati", realModel: "Maserati GranTurismo MC" },
  "Fusilade": { manufacturer: "Schyster", realModel: "Chrysler Crossfire" },
  "Futo GTX": { manufacturer: "Karin", realModel: "Toyota AE86 Trueno" },
  "Futo": { manufacturer: "Karin", realModel: "Toyota AE86 Levin" },
  "GB200": { manufacturer: "Vapid", realModel: "Ford RS200" },
  "Growler": { manufacturer: "Pfister", realModel: "Porsche 718 Cayman GT4" },
  "Hotring Sabre": { manufacturer: "Declasse", realModel: "Chevrolet Monte Carlo NASCAR" },
  "Imorgon": { manufacturer: "Overflod", realModel: "Polestar Precept" },
  "Itali GTO": { manufacturer: "Grotti", realModel: "Ferrari 812 Superfast" },
  "Itali RSX": { manufacturer: "Grotti", realModel: "Ferrari SF90 Stradale" },
  "Issi Sport": { manufacturer: "Weeny", realModel: "Mini JCW GP" },
  "Jester": { manufacturer: "Dinka", realModel: "Acura NSX (2016)" },
  "Jester (Course)": { manufacturer: "Dinka", realModel: "Acura NSX GT3" },
  "Jester classique": { manufacturer: "Dinka", realModel: "Toyota Supra Mk4" },
  "Jester RR": { manufacturer: "Dinka", realModel: "Toyota Supra Mk5" },
  "Jugular": { manufacturer: "Ocelot", realModel: "Jaguar XE SV Project 8" },
  "Khamelion": { manufacturer: "Hijak", realModel: "Fisker Karma" },
  "Komoda": { manufacturer: "Lampadati", realModel: "Alfa Romeo Giulia" },
  "Kuruma": { manufacturer: "Karin", realModel: "Mitsubishi Lancer Evo X" },
  "Locust": { manufacturer: "Ocelot", realModel: "Lotus 3-Eleven" },
  "Lynx": { manufacturer: "Ocelot", realModel: "Jaguar F-Type" },
  "Massacro": { manufacturer: "Dewbauchee", realModel: "Aston Martin V12 Zagato" },
  "Massacro (Course)": { manufacturer: "Dewbauchee", realModel: "Aston Martin V12 Zagato GT3" },
  "Neo": { manufacturer: "Vysser", realModel: "Spyker C8" },
  "Neon": { manufacturer: "Pfister", realModel: "Porsche Taycan" },
  "Omnis": { manufacturer: "Obey", realModel: "Audi Sport Quattro" },
  "Paragon R": { manufacturer: "Enus", realModel: "Bentley Continental GT" },
  "Pariah": { manufacturer: "Ocelot", realModel: "Ferrari 812 / Aston Martin V12 Vantage" },
  "Penumbra": { manufacturer: "Maibatsu", realModel: "Mitsubishi Eclipse" },
  "Penumbra FF": { manufacturer: "Maibatsu", realModel: "Mitsubishi Eclipse (4th Gen)" },
  "Raiden": { manufacturer: "Coil", realModel: "Tesla Model S" },
  "Rapid GT": { manufacturer: "Dewbauchee", realModel: "Aston Martin V8 Vantage" },
  "Rapid GT Cabrio": { manufacturer: "Dewbauchee", realModel: "Aston Martin V8 Vantage Roadster" },
  "Raptor": { manufacturer: "BF", realModel: "KTM X-Bow" },
  "Remus": { manufacturer: "Annis", realModel: "Nissan Silvia S13" },
  "RT3000": { manufacturer: "Dinka", realModel: "Honda S2000" },
  "Ruston": { manufacturer: "Hijak", realModel: "Ariel Atom" },
  "Schafter LWB": { manufacturer: "Benefactor", realModel: "Mercedes-Maybach S-Class" },
  "Schafter V12": { manufacturer: "Benefactor", realModel: "Mercedes-Benz S65 AMG" },
  "Schlagen GT": { manufacturer: "Benefactor", realModel: "Mercedes-AMG GT" },
  "Schwartzer": { manufacturer: "Benefactor", realModel: "Mercedes-Benz C63 AMG" },
  "Sentinel Classique": { manufacturer: "Ubermacht", realModel: "BMW E30 M3" },
  "Seven 70": { manufacturer: "Dewbauchee", realModel: "Aston Martin One-77" },
  "Specter": { manufacturer: "Dewbauchee", realModel: "Aston Martin DB11" },
  "Specter Custom": { manufacturer: "Dewbauchee", realModel: "Aston Martin DB11 Custom" },
  "Streiter": { manufacturer: "Benefactor", realModel: "Mercedes-Benz E63 AMG Wagon" },
  "Sugoi": { manufacturer: "Dinka", realModel: "Honda Civic Type R FK8" },
  "Sultan": { manufacturer: "Karin", realModel: "Subaru Impreza WRX STI" },
  "Sultan Classique": { manufacturer: "Karin", realModel: "Subaru Legacy RS" },
  "Tropos Rallye": { manufacturer: "Lampadati", realModel: "Lancia Stratos" },
  "Vectre": { manufacturer: "Emperor", realModel: "Lexus RC F" },
  "Veto Classique": { manufacturer: "Grotti", realModel: "Go-Kart Classic" },
  "Veto Moderne": { manufacturer: "Grotti", realModel: "Go-Kart Modern" },
  "Verlierer": { manufacturer: "Bravado", realModel: "Wiesmann GT MF5" },
  "V-STR": { manufacturer: "Albany", realModel: "Cadillac CT6-V" },
  "ZR350": { manufacturer: "Annis", realModel: "Mazda RX-7 FD" },
  "Comet S2 Cabrio": { manufacturer: "Pfister", realModel: "Porsche 911 (992) Cabriolet" },
  "300R": { manufacturer: "Annis", realModel: "Nissan 300ZX Z32" },
  "Corsita": { manufacturer: "Lampadati", realModel: "Alfa Romeo 4C" },
  "9F": { manufacturer: "Obey", realModel: "Audi R8" },
  "9F Cabrio": { manufacturer: "Obey", realModel: "Audi R8 Spyder" },
  "Itali GTO Stinger TT": { manufacturer: "Grotti", realModel: "Ferrari 812 Competizione" },
  "La Coureuse": { manufacturer: "Truffade", realModel: "Bugatti Divo" },
  "Hotring Hellfire": { manufacturer: "Bravado", realModel: "Dodge Charger NASCAR" },
  "Sultan RS Classique": { manufacturer: "Karin", realModel: "Subaru Impreza 22B STI" },
  "Surano": { manufacturer: "Benefactor", realModel: "Mercedes-Benz SLS AMG" },
  "8F Drafter": { manufacturer: "Obey", realModel: "Audi RS e-tron GT" },
  "Bison": { manufacturer: "Bravado", realModel: "Dodge Ram" },
  "Bobcat XL": { manufacturer: "Vapid", realModel: "Ford Ranger" },
  "Burrito": { manufacturer: "Declasse", realModel: "Chevrolet Express Van" },
  "Burrito II (Enneigée)": { manufacturer: "Declasse", realModel: "Chevrolet Express (Snow)" },
  "Camper": { manufacturer: "Brute", realModel: "GMC Vandura Camper" },
  "Van de Clown": { manufacturer: "Vapid", realModel: "Ford Econoline Clown" },
  "Journey": { manufacturer: "Zirconium", realModel: "Winnebago RV" },
  "Minivan": { manufacturer: "Vapid", realModel: "Ford Aerostar" },
  "Minivan Custom": { manufacturer: "Vapid", realModel: "Ford Aerostar Custom" },
  "Paradise": { manufacturer: "Bravado", realModel: "Dodge Caravan" },
  "Pony": { manufacturer: "Brute", realModel: "Chevrolet Step Van" },
  "Rumpo Custom": { manufacturer: "Bravado", realModel: "Dodge Ram Van Custom" },
  "Speedo": { manufacturer: "Vapid", realModel: "Ford Transit Connect" },
  "Surfer": { manufacturer: "BF", realModel: "Volkswagen Type 2" },
  "Surfer II (Sale)": { manufacturer: "BF", realModel: "Volkswagen Type 2 (Dirty)" },
  "Youga": { manufacturer: "Bravado", realModel: "Dodge Ram Van" },
  "Youga Classique": { manufacturer: "Bravado", realModel: "Dodge Ram Van Classic" },
  "Youga Classique 4x4": { manufacturer: "Bravado", realModel: "Dodge Ram Van 4x4" },
  "Burrito de Gang": { manufacturer: "Declasse", realModel: "Chevrolet Express (Gang)" },
  "Burrito de Gang II": { manufacturer: "Declasse", realModel: "Chevrolet Express (Gang)" },
  "Journey II": { manufacturer: "Zirconium", realModel: "Winnebago RV (Modern)" },
  "Surfer Custom": { manufacturer: "BF", realModel: "Volkswagen Type 2 Custom" },
  "Akuma": { manufacturer: "Dinka", realModel: "Honda CBR1000RR" },
  "Avarus": { manufacturer: "Western", realModel: "Harley-Davidson Softail" },
  "Bagger": { manufacturer: "Western", realModel: "Harley-Davidson Street Glide" },
  "Bati 801": { manufacturer: "Pegassi", realModel: "Ducati 848" },
  "Bati 801RR": { manufacturer: "Pegassi", realModel: "Ducati 1199 Panigale" },
  "BF400": { manufacturer: "Nagasaki", realModel: "Kawasaki KX450F" },
  "Carbon RS": { manufacturer: "Nagasaki", realModel: "Kawasaki Ninja H2" },
  "Chimera": { manufacturer: "Nagasaki", realModel: "Polaris Slingshot" },
  "Cliffhanger": { manufacturer: "Western", realModel: "Harley-Davidson Sportster" },
  "Daemon": { manufacturer: "Western", realModel: "Harley-Davidson Fat Bob" },
  "Daemon II": { manufacturer: "Western", realModel: "Harley-Davidson Fat Bob Custom" },
  "BMX": { manufacturer: "Generic", realModel: "BMX Bike" },
  "Cruiser": { manufacturer: "Generic", realModel: "Beach Cruiser" },
  "Fixter": { manufacturer: "Generic", realModel: "Fixie Bike" },
  "Scorcher": { manufacturer: "Generic", realModel: "Mountain Bike" },
  "Whippet": { manufacturer: "Generic", realModel: "Road Bike" },
  "Endurex": { manufacturer: "Generic", realModel: "Racing Bike" },
  "Tri-Cycles": { manufacturer: "Generic", realModel: "Racing Bike" },
  "Zombie Bobber": { manufacturer: "Western", realModel: "Harley-Davidson Bobber" },
  "Zombie Chopper": { manufacturer: "Western", realModel: "Harley-Davidson Chopper" },
  "Defiler": { manufacturer: "Shitzu", realModel: "Suzuki GSX-R600" },
  "Diabolus": { manufacturer: "Principe", realModel: "Ducati Scrambler" },
  "Diabolus Custom": { manufacturer: "Principe", realModel: "Ducati Scrambler Custom" },
  "Double-T": { manufacturer: "Dinka", realModel: "Honda CBR600RR" },
  "Enduro": { manufacturer: "Dinka", realModel: "Honda CRF450R" },
  "Esskey": { manufacturer: "Pegassi", realModel: "Ducati Scrambler" },
  "Faggio Sport": { manufacturer: "Pegassi", realModel: "Piaggio Vespa Sprint" },
  "Faggio Mod": { manufacturer: "Pegassi", realModel: "Piaggio Vespa Mod" },
  "FCR 1000": { manufacturer: "Pegassi", realModel: "Ducati Sport Classic" },
  "FCR 1000 Custom": { manufacturer: "Pegassi", realModel: "Ducati Sport Classic Custom" },
  "Gargoyle": { manufacturer: "Western", realModel: "KTM Duke Custom" },
  "Hakuchou": { manufacturer: "Shitzu", realModel: "Suzuki Hayabusa" },
  "Hackuchou Drag": { manufacturer: "Shitzu", realModel: "Suzuki Hayabusa Drag" },
  "Hexer": { manufacturer: "Western", realModel: "Harley-Davidson Dyna" },
  "Innovation": { manufacturer: "Western", realModel: "Harley-Davidson Chopper" },
  "Manchez": { manufacturer: "Maibatsu", realModel: "Honda CRF250L" },
  "Manchez Scout": { manufacturer: "Maibatsu", realModel: "Honda CRF250L Rally" },
  "Nemesis": { manufacturer: "Principe", realModel: "Aprilia RSV4" },
  "Nightblade": { manufacturer: "Western", realModel: "Harley-Davidson V-Rod" },
  "PCJ 600": { manufacturer: "Shitzu", realModel: "Suzuki GSX-R750" },
  "Rampant Rocket": { manufacturer: "Western", realModel: "Triumph Rocket III" },
  "Rat Bike": { manufacturer: "Western", realModel: "Custom Rat Bike" },
  "Ruffian": { manufacturer: "Pegassi", realModel: "KTM 690 Duke" },
  "Sanchez": { manufacturer: "Maibatsu", realModel: "Honda XR650R" },
  "Sanchez (Couleurs)": { manufacturer: "Maibatsu", realModel: "Honda XR650R" },
  "Sanctus": { manufacturer: "Western", realModel: "Custom Chopper" },
  "Sovereign": { manufacturer: "Western", realModel: "Harley-Davidson Electra Glide" },
  "Stryder": { manufacturer: "Nagasaki", realModel: "Honda Grom" },
  "Thrust": { manufacturer: "Dinka", realModel: "Honda NM4 Vultus" },
  "Vader": { manufacturer: "Shitzu", realModel: "Yamaha MT-09" },
  "Vindicator": { manufacturer: "Dinka", realModel: "Honda CTX1300" },
  "Vortex": { manufacturer: "Nagasaki", realModel: "Kawasaki Ninja 650" },
  "Wolfsbane": { manufacturer: "Western", realModel: "Harley-Davidson Sportster" },
  "Lectro": { manufacturer: "Principe", realModel: "Alta Motors Redshift" },
  "Shinobi": { manufacturer: "Nagasaki", realModel: "Kawasaki Ninja ZX-10R" },
  "Reever": { manufacturer: "Western", realModel: "Confederate X132 Hellcat" },
  "Powersurge": { manufacturer: "Dinka", realModel: "Zero SR/F" },
  "Manchez Scout C": { manufacturer: "Maibatsu", realModel: "Honda CRF250L Rally" },
  "Inductor Junk Energy": { manufacturer: "Pegassi", realModel: "Electric Bike (Custom)" },
  "Inductor": { manufacturer: "Pegassi", realModel: "Electric Superbike" },
  "190z": { manufacturer: "Karin", realModel: "Datsun 240Z" },
  "Casco": { manufacturer: "Lampadati", realModel: "Maserati 3500 GT" },
  "Cheburek": { manufacturer: "Rune", realModel: "Lada 2105" },
  "Cheetah Classique": { manufacturer: "Grotti", realModel: "Ferrari Testarossa" },
  "Coquette Classique": { manufacturer: "Invetero", realModel: "Chevrolet Corvette C2" },
  "Dynasty": { manufacturer: "Weeny", realModel: "Morris Minor" },
  "Fagaloa": { manufacturer: "Vulcar", realModel: "Volvo Duett" },
  "Franken Stange": { manufacturer: "Albany", realModel: "Custom Hot Rod" },
  "GT500": { manufacturer: "Grotti", realModel: "Ferrari 250 GT SWB" },
  "Infernus Classique": { manufacturer: "Pegassi", realModel: "Lamborghini Diablo" },
  "Revolter": { manufacturer: "Ubermacht", realModel: "BMW M5 (E28)" },
  "Buffalo STX": { manufacturer: "Bravado", realModel: "Dodge Charger Hellcat" },
  "JB 700W": { manufacturer: "Dewbauchee", realModel: "Aston Martin DB5" },
  "Mamba": { manufacturer: "Declasse", realModel: "AC Cobra" },
  "Manana": { manufacturer: "Albany", realModel: "Chevrolet Monte Carlo" },
  "Michelli GT": { manufacturer: "Lampadati", realModel: "Alfa Romeo Giulia Sprint GT" },
  "Monroe": { manufacturer: "Pegassi", realModel: "Lamborghini Miura" },
  "Nebula Turbo": { manufacturer: "Vulcar", realModel: "Volvo 242 Turbo" },
  "Peyote": { manufacturer: "Vapid", realModel: "Ford Thunderbird" },
  "Peyote Custom": { manufacturer: "Vapid", realModel: "Ford Thunderbird Custom" },
  "Pigalle": { manufacturer: "Lampadati", realModel: "Citroën SM" },
  "Rapid GT Classique": { manufacturer: "Dewbauchee", realModel: "Aston Martin V8 (1970s)" },
  "Retinue": { manufacturer: "Vapid", realModel: "Ford Escort Mk1" },
  "Roosevelt": { manufacturer: "Albany", realModel: "Cord 812" },
  "Roosevelt Valor": { manufacturer: "Albany", realModel: "Cord 812 Phaeton" },
  "Savestra": { manufacturer: "Annis", realModel: "Mazda RX-3" },
  "Stinger": { manufacturer: "Grotti", realModel: "Ferrari 250 GTO" },
  "Stinger GT": { manufacturer: "Grotti", realModel: "Ferrari 250 GTO Cabrio" },
  "Stirling GT": { manufacturer: "Benefactor", realModel: "Mercedes-Benz 300SL" },
  "Swinger": { manufacturer: "Ocelot", realModel: "Jaguar E-Type" },
  "Tornado": { manufacturer: "Declasse", realModel: "Chevrolet Bel Air" },
  "Tornado II (Convertible)": { manufacturer: "Declasse", realModel: "Chevrolet Bel Air Convertible" },
  "Tornado III (Rouillée)": { manufacturer: "Declasse", realModel: "Chevrolet Bel Air (Rusty)" },
  "Tornado IIII (Très rouillée)": { manufacturer: "Declasse", realModel: "Chevrolet Bel Air (Very Rusty)" },
  "Tornado Custom": { manufacturer: "Declasse", realModel: "Chevrolet Bel Air Custom" },
  "Tornado Rat Rod": { manufacturer: "Declasse", realModel: "Chevrolet Bel Air Rat Rod" },
  "Turismo Classique": { manufacturer: "Grotti", realModel: "Ferrari F40" },
  "Zion Classique": { manufacturer: "Ubermacht", realModel: "BMW E24 6 Series" },
  "Z-Type": { manufacturer: "Truffade", realModel: "Bugatti Type 57 Atlantic" },
  "Hotring Everon": { manufacturer: "Karin", realModel: "Toyota Tundra NASCAR" },
  "Panthere": { manufacturer: "Toundra", realModel: "De Tomaso Pantera" },
  "Omnis e-GT": { manufacturer: "Obey", realModel: "Audi RS e-tron GT" },
  "SM722": { manufacturer: "Benefactor", realModel: "Mercedes-Benz 300 SLR" },
  "811": { manufacturer: "Pfister", realModel: "Porsche 918 Spyder" },
  "Adder": { manufacturer: "Truffade", realModel: "Bugatti Veyron" },
  "Autarch": { manufacturer: "Overflod", realModel: "SCG 003S" },
  "Banshee 900R": { manufacturer: "Bravado", realModel: "Dodge Viper ACR" },
  "Bullet": { manufacturer: "Vapid", realModel: "Ford GT (2005)" },
  "Cheetah": { manufacturer: "Grotti", realModel: "Ferrari Enzo" },
  "Cyclone": { manufacturer: "Coil", realModel: "Rimac Concept One" },
  "Deveste Eight": { manufacturer: "Principe", realModel: "Devel Sixteen" },
  "Emerus": { manufacturer: "Progen", realModel: "McLaren Senna" },
  "Entity XF": { manufacturer: "Overflod", realModel: "Koenigsegg CCX" },
  "Entity XXR": { manufacturer: "Overflod", realModel: "Koenigsegg One:1" },
  "FMJ": { manufacturer: "Vapid", realModel: "Ford GT (2017)" },
  "GP1": { manufacturer: "Progen", realModel: "McLaren F1" },
  "Infernus": { manufacturer: "Pegassi", realModel: "Lamborghini Murciélago" },
  "Itali GTB": { manufacturer: "Progen", realModel: "McLaren 570S" },
  "Itali GTB Custom": { manufacturer: "Progen", realModel: "McLaren 570S Custom" },
  "Krieger": { manufacturer: "Benefactor", realModel: "Mercedes-AMG Project One" },
  "Le Bélier": { manufacturer: "Truffade", realModel: "Bugatti Chiron Super Sport" },
  "Nero": { manufacturer: "Truffade", realModel: "Bugatti Chiron" },
  "Nero Custom": { manufacturer: "Truffade", realModel: "Bugatti Chiron Custom" },
  "Osiris": { manufacturer: "Pegassi", realModel: "Pagani Huayra" },
  "Penetrator": { manufacturer: "Ocelot", realModel: "Jaguar XJ220" },
  "RE-7B": { manufacturer: "Annis", realModel: "Mazda 787B" },
  "Reaper": { manufacturer: "Pegassi", realModel: "Lykan HyperSport" },
  "S80RR": { manufacturer: "Annis", realModel: "Nissan R390 GT1" },
  "SC1": { manufacturer: "Ubermacht", realModel: "BMW i8" },
  "Scramjet": { manufacturer: "Declasse", realModel: "Mach Five" },
  "Sultan RS": { manufacturer: "Karin", realModel: "Subaru WRX STI" },
  "Supercarlite": { manufacturer: "Grotti", realModel: "Ferrari LaFerrari" },
  "T20": { manufacturer: "Progen", realModel: "McLaren P1" },
  "Taipan": { manufacturer: "Cheval", realModel: "Hennessey Venom F5" },
  "Tempesta": { manufacturer: "Pegassi", realModel: "Lamborghini Huracán" },
  "Tezeract": { manufacturer: "Pegassi", realModel: "Lamborghini Terzo Millennio" },
  "Thrax": { manufacturer: "Truffade", realModel: "Bugatti Divo" },
  "Tigon": { manufacturer: "Lampadati", realModel: "Lamborghini Sián" },
  "Torero": { manufacturer: "Pegassi", realModel: "Lamborghini Countach" },
  "Turismo R": { manufacturer: "Grotti", realModel: "Ferrari LaFerrari" },
  "Tyrant": { manufacturer: "Overflod", realModel: "Apollo Intensa Emozione" },
  "Tyrus": { manufacturer: "Progen", realModel: "McLaren P1 GTR" },
  "Vacca": { manufacturer: "Pegassi", realModel: "Lamborghini Gallardo" },
  "Vagner": { manufacturer: "Dewbauchee", realModel: "Aston Martin Valkyrie" },
  "Vigilante": { manufacturer: "Grotti", realModel: "Batmobile (1989)" },
  "Visione": { manufacturer: "Grotti", realModel: "Ferrari Xezri Concept" },
  "Voltic": { manufacturer: "Coil", realModel: "Tesla Roadster" },
  "X80 Proto": { manufacturer: "Grotti", realModel: "Ferrari F80 Concept" },
  "XA-21": { manufacturer: "Ocelot", realModel: "Jaguar C-X75" },
  "Zentorno": { manufacturer: "Pegassi", realModel: "Lamborghini Sesto Elemento" },
  "Zorrusso": { manufacturer: "Pegassi", realModel: "Italdesign Zerouno" },
  "Furia": { manufacturer: "Grotti", realModel: "Ferrari F8 Tributo" },
  "Ignus": { manufacturer: "Pegassi", realModel: "Lamborghini Essenza SCV12" },
  "Zeno": { manufacturer: "Overflod", realModel: "Zenvo TSR-S" },
  "Champion": { manufacturer: "Dewbauchee", realModel: "Aston Martin Victor" },
  "Virtue": { manufacturer: "Ocelot", realModel: "McLaren Speedtail" },
  "Torero XO": { manufacturer: "Pegassi", realModel: "Lamborghini Countach LPI 800-4" },
  "Weaponized Ignus": { manufacturer: "Pegassi", realModel: "Lamborghini Essenza SCV12 (Armed)" },
  "Nyx": { manufacturer: "Pegassi", realModel: "Lamborghini Revuelto" },
  "Eurosx2": { manufacturer: "Annis", realModel: "Nissan Silvia S15 (Widebody)" },
  "Bullet GT": { manufacturer: "Vapid", realModel: "Ford GT40" },
  "Blade": { manufacturer: "Vapid", realModel: "Ford Falcon" },
  "Broadway": { manufacturer: "Classique", realModel: "Cadillac Series 62" },
  "Buccaneer": { manufacturer: "Albany", realModel: "Buick Riviera" },
  "Buccaneer Custom": { manufacturer: "Albany", realModel: "Buick Riviera Custom" },
  "Chino": { manufacturer: "Vapid", realModel: "Chevrolet Impala (1960s)" },
  "Chino Custom": { manufacturer: "Vapid", realModel: "Chevrolet Impala Custom" },
  "Clique": { manufacturer: "Vapid", realModel: "Ford Model B" },
  "Coquette BlackFin": { manufacturer: "Invetero", realModel: "Chevrolet Corvette C1" },
  "Deviant": { manufacturer: "Schyster", realModel: "Plymouth Cuda" },
  "Dominator": { manufacturer: "Vapid", realModel: "Ford Mustang (2013)" },
  "Dominator GTT": { manufacturer: "Vapid", realModel: "Ford Mustang Boss 302" },
  "Dominator GTX": { manufacturer: "Vapid", realModel: "Ford Mustang (2018)" },
  "Dominator ASP": { manufacturer: "Vapid", realModel: "Ford Mustang Shelby GT500" },
  "Dominator GT": { manufacturer: "Vapid", realModel: "Ford Mustang (2024)" },
  "Dukes": { manufacturer: "Imponte", realModel: "Dodge Charger (1969)" },
  "Ellie": { manufacturer: "Vapid", realModel: "Ford Mustang Shelby GT500 (1967)" },
  "Eudora": { manufacturer: "Willard", realModel: "Buick Grand National" },
  "Faction": { manufacturer: "Willard", realModel: "Buick Regal" },
  "Faction Custom": { manufacturer: "Willard", realModel: "Buick Regal Custom" },
  "Faction Custom Donk": { manufacturer: "Willard", realModel: "Buick Regal Donk" },
  "Gauntlet": { manufacturer: "Bravado", realModel: "Dodge Challenger" },
  "Gauntlet Hellfire": { manufacturer: "Bravado", realModel: "Dodge Challenger SRT Demon" },
  "Gauntlet Classique": { manufacturer: "Bravado", realModel: "Dodge Challenger (1970)" },
  "Gauntlet Classique Custom": { manufacturer: "Bravado", realModel: "Dodge Challenger (1970) Custom" },
  "Greenwood": { manufacturer: "Bravado", realModel: "Dodge Diplomat" },
  "Hermes": { manufacturer: "Albany", realModel: "Mercury Eight" },
  "Hotknife": { manufacturer: "Vapid", realModel: "Custom Hot Rod" },
  "Hustler": { manufacturer: "Vapid", realModel: "Custom Hot Rod" },
  "Impaler": { manufacturer: "Declasse", realModel: "Chevrolet Impala (1967)" },
  "Impaler SZ": { manufacturer: "Declasse", realModel: "Chevrolet Impala (1967) SZ" },
  "Lurcher": { manufacturer: "Albany", realModel: "Cadillac Hearse Hot Rod" },
  "Moonbeam": { manufacturer: "Declasse", realModel: "Chevrolet Astro" },
  "Moonbeam Custom": { manufacturer: "Declasse", realModel: "Chevrolet Astro Custom" },
  "Nightshade": { manufacturer: "Imponte", realModel: "Oldsmobile Cutlass 442" },
  "Peyote Gasser": { manufacturer: "Vapid", realModel: "Ford Thunderbird Gasser" },
  "Phoenix": { manufacturer: "Imponte", realModel: "Pontiac Firebird Trans Am" },
  "Picador": { manufacturer: "Cheval", realModel: "Chevrolet El Camino" },
  "Rat-Loader": { manufacturer: "Bravado", realModel: "Custom Rat Rod Pickup" },
  "Rat-Truck": { manufacturer: "Bravado", realModel: "Custom Rat Rod Truck" },
  "Ruiner": { manufacturer: "Imponte", realModel: "Pontiac Firebird (1982)" },
  "Ruiner 2000": { manufacturer: "Imponte", realModel: "KITT (Knight Rider)" },
  "Ruiner ZZ-8": { manufacturer: "Imponte", realModel: "Pontiac Firebird Trans Am" },
  "Sabre Turbo": { manufacturer: "Declasse", realModel: "Oldsmobile 442" },
  "Sabre Turbo Custom": { manufacturer: "Declasse", realModel: "Oldsmobile 442 Custom" },
  "Slamvan": { manufacturer: "Vapid", realModel: "Custom Van" },
  "Slamvan Custom": { manufacturer: "Vapid", realModel: "Custom Van Custom" },
  "Slamtruck": { manufacturer: "Vapid", realModel: "Custom Flatbed" },
  "Stallion": { manufacturer: "Declasse", realModel: "Ford Torino" },
  "Tampa": { manufacturer: "Declasse", realModel: "Ford Maverick" },
  "Tulip": { manufacturer: "Declasse", realModel: "Chevrolet Chevelle" },
  "Tulip M-100": { manufacturer: "Declasse", realModel: "Chevrolet Chevelle SS" },
  "Vamos": { manufacturer: "Declasse", realModel: "AMC AMX" },
  "Vigero": { manufacturer: "Declasse", realModel: "Chevrolet Camaro (1969)" },
  "Vigero ZX": { manufacturer: "Declasse", realModel: "Chevrolet Camaro ZL1" },
  "Virgo": { manufacturer: "Albany", realModel: "Mercury Cougar" },
  "Virgo Classique": { manufacturer: "Dundreary", realModel: "Lincoln Continental Mark IV" },
  "Virgo Classique Custom": { manufacturer: "Dundreary", realModel: "Lincoln Continental Mark IV Custom" },
  "Voodoo": { manufacturer: "Declasse", realModel: "Chevrolet Impala (1960)" },
  "Voodoo Custom": { manufacturer: "Declasse", realModel: "Chevrolet Impala Custom" },
  "Weevil Custom": { manufacturer: "BF", realModel: "Volkswagen Beetle Custom" },
  "Yosemite": { manufacturer: "Declasse", realModel: "Chevrolet C10 Stepside" },
  "Yosemite Rancher": { manufacturer: "Declasse", realModel: "Chevrolet K10 Blazer" },
  "Brigham": { manufacturer: "Bravado", realModel: "Dodge D-Series" },
  "Tahoma Coupé": { manufacturer: "Declasse", realModel: "Chevrolet Monte Carlo Lowrider" },
  "Manana Custom": { manufacturer: "Albany", realModel: "Chevrolet Monte Carlo Custom" },
  "Freeway": { manufacturer: "Western", realModel: "Harley-Davidson Road King" },
  "Redwood Gauntlet": { manufacturer: "Bravado", realModel: "Dodge Challenger (Redwood)" },
  "Pisswasser Dominator": { manufacturer: "Vapid", realModel: "Ford Mustang (Pisswasser)" },
  "Burger Shot Stallion": { manufacturer: "Declasse", realModel: "Ford Torino (Burger Shot)" },
  "Sprunk Buffalo": { manufacturer: "Bravado", realModel: "Dodge Charger (Sprunk)" },
  "Dukes (Rouillée)": { manufacturer: "Imponte", realModel: "Dodge Charger (1969) Rusty" },
  "Lost Slamvan": { manufacturer: "Vapid", realModel: "Custom Van (Lost MC)" },
};

async function main() {
  console.log("🔧 Adding manufacturer and realname columns to vehicles table...");

  try {
    await sql`ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(255)`;
    console.log("✅ manufacturer column added");
  } catch (error: any) {
    if (error.message?.includes("already exists")) {
      console.log("ℹ️ manufacturer column already exists");
    } else {
      throw error;
    }
  }

  try {
    await sql`ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS realname VARCHAR(255)`;
    console.log("✅ realname column added");
  } catch (error: any) {
    if (error.message?.includes("already exists")) {
      console.log("ℹ️ realname column already exists");
    } else {
      throw error;
    }
  }

  console.log("\n📊 Updating vehicles with manufacturer and realname data...");
  
  let updated = 0;
  let notFound = 0;
  const notFoundNames: string[] = [];

  for (const [vehicleName, data] of Object.entries(vehicleData)) {
    const result = await sql`
      UPDATE vehicles 
      SET manufacturer = ${data.manufacturer}, realname = ${data.realModel}
      WHERE LOWER(TRIM(name)) = LOWER(TRIM(${vehicleName}))
      RETURNING id, name
    `;
    
    if (result.length > 0) {
      updated++;
      console.log(`✅ Updated: ${vehicleName} -> ${data.manufacturer} / ${data.realModel}`);
    } else {
      notFound++;
      notFoundNames.push(vehicleName);
    }
  }

  console.log(`\n📈 Summary:`);
  console.log(`   ✅ Updated: ${updated} vehicles`);
  console.log(`   ❌ Not found: ${notFound} vehicles`);
  
  if (notFoundNames.length > 0) {
    console.log(`\n⚠️ Vehicles not found in database:`);
    notFoundNames.forEach(name => console.log(`   - ${name}`));
  }

  const sample = await sql`SELECT id, name, manufacturer, realname FROM vehicles LIMIT 5`;
  console.log("\n📋 Sample data:");
  console.table(sample);
}

main().catch(console.error);
